services:
  - docker

env:
  global:
    - IMAGE_NAME=diuis/docker-debian9-base

script:
  - docker build . -t "$IMAGE_NAME"

before_deploy:
  - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_USERNAME"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}"
  on:
    branch: master